name: bestapp_package
description: A new Flutter package project.
version: 5.0.2
homepage: https://repo.besoft.com.br/steeve
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  talker_dio_logger: ^4.5.5
  intl: ^0.20.2
  # toast: ^0.3.0
  flash: ^3.0.5+1
  path_provider: ^2.2.0
  cached_network_image: ^3.4.0
  email_validator: ^3.0.0
  shimmer: ^2.0.0
  loading_animation_widget: ^1.2.0+4
  # device_info_plus: ^9.1.2
  device_info_plus: ^12.1.0
  cookie_jar: ^4.0.8
  cpfcnpj:
    git:
      url: https://github.com/erickhaendel/dart-cpfcnpj.git
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
      ref: master
  
  # flutter_image_compress: ^2.1.0
  # essa parte do git e para o suporte a wasm
  # flutter_image_compress_web:
  #   git:
  #     url: https://github.com/myxzlpltk/flutter_image_compress.git
  #     path: packages/flutter_image_compress_web
  
dev_dependencies:
  flutter_test:
    sdk: flutter